name: Continuous Integration

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-compose-action@v1

      - name: Build Docker Image
        run: docker compose up -d
          
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-compose-action@v1

      - name: Test Flask API
        run: docker compose run api python -m unittest discover

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"