name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Docker
        run: |
          docker compose up
          docker compose run api python -m unittest discover