name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Teste
        uses: actions/checkout@v3

      - name: Build and Test Docker
        run: |
          docker-compose up -d
          docker-compose run api python -m unittest discover