name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build and Test Docker
        run: |
          docker-compose up -d
          docker-compose run api python -m unittest discover